---

# Back end

- name: Remove build directory
  tags:
    - remove-build-directory
  file:
    path: "{{ build_dir }}"
    state: absent

- name: Remove build archive
  tags:
    - archive
    - remove-build-archive
  file:
    path: "{{ build_archive }}"
    state: absent

- name: Create build directory structure
  tags:
    - prepare-build-dir
  file:
    path: "{{ build_dir }}/{{ item }}"
    state: directory
  with_items:
    - dist

- name: Add in-progress/unfinished marker to build directory
  copy:
    content: "DEPLOY_UNFINISHED"
    dest: "{{ build_dir }}/DEPLOY_UNFINISHED"

- name: Copy WSGI module to build directory
  tags:
    - prepare-copy-files
  template:
    src: "{{ wsgi_module }}"
    dest: "{{ build_dir }}"

- name: Copy settings file to build directory
  tags:
    - prepare-copy-files
  template:
    src: "{{ local_settings_file }}"
    dest: "{{ build_dir }}"

- name: Copy RunCommands console script wrapper to build directory
  tags:
    - prepare-copy-files
  template:
    src: "run.j2"
    dest: "{{ build_dir }}/run"
    mode: 0750

- name: Copy RunCommands module to build directory
  tags:
    - prepare-copy-files
  copy:
    src: "{{ root }}/commands.py"
    dest: "{{ build_dir }}"

- name: Copy RunCommands config to build directory
  tags:
    - prepare-copy-files
  copy:
    src: "{{ root }}/commands.toml"
    dest: "{{ build_dir }}"

- name: Remove existing source distributions
  tags:
      - build-distributions
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ root }}/dist"
      - "{{ core_root }}/dist"

- name: Build source distributions
  tags:
    - build-distributions
  command: poetry build -f wheel
  args:
    chdir: "{{ item }}"
  with_items:
    - "{{ root }}"
    - "{{ core_root }}"

- name: Copy source distributions to build directory
  tags:
      - build-distributions
  copy:
      src: "{{ item }}"
      dest: "{{ build_dir }}/dist/"
  with_fileglob:
      - "{{ root }}/dist/*"
      - "{{ core_root }}/dist/*"

# Build archive

- name: Create build archive
  tags:
    - archive
    - create-build-archive
  archive:
    path: "{{ build_dir }}"
    dest: "{{ build_archive }}"
