#!/bin/sh
export USER=bycycle
exec 2>&1
prefix=/home/bycycle/Projects/byCycle/trunk.env
source "${prefix}/bin/activate"
cmd="${prefix}/bin/python -u ../serve.py one"
echo $cmd
if test $UID -eq 0; then
    exec setuidgid bycycle $cmd
else
    exec $cmd
fi

